version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0

x-env-newrelic: &env-newrelic
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NEW_RELIC_TURN_OFF_SAMPLER: ${NEW_RELIC_TURN_OFF_SAMPLER-}

x-env-mongo: &env-mongo
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
  ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}

x-env-elastic: &env-elastic
  ELASTICSEARCH_URL: ${ELASTICSEARCH_URL-http://elasticsearch:9200}

x-env-tauron: &env-tauron
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.tauron.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.tauron.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.tauron.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.tauron.base.parameter1.com}

x-env-virgon: &env-virgon
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.virgon.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.virgon.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.virgon.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.virgon.base.parameter1.com}

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /base-cms
  volumes:
    - .:/base-cms:cached
    - ./node_modules:/base-cms/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /base-cms
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "10000:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      server.name: kibana
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL-http://elasticsearch:9200}"
      LOGGING_QUIET: "true"
    depends_on:
      - elasticsearch
    ports:
      - "10001:5601"

  redis:
    tty: true
    image: redis:6.0-alpine
    ports:
      - "10002:6379"

  keyword-analysis:
    << : *node
    working_dir: /base-cms/services/keyword-analysis
    command: ["src"]
    environment:
      <<: [*env, *env-mongo, *env-newrelic, *env-elastic]
    depends_on:
      - mongodb
      - elasticsearch
      - kibana

  # GRAPHQL

  graphql-server:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-mongo, *env-newrelic]
      REDIS_CACHE_DSN: ${REDIS_CACHE_DSN-redis://redis}
      GRAPHQL_CACHE_CONTROL_ENABLED: ${GRAPHQL_CACHE_CONTROL_ENABLED-false}
      GRAPHQL_DEBUG_ENABLED: ${GRAPHQL_DEBUG_ENABLED-false}
      GRAPHQL_INTROSPECTION_ENABLED: ${GRAPHQL_INTROSPECTION_ENABLED-true}
      GRAPHQL_PLAYGROUND_ENABLED: ${GRAPHQL_PLAYGROUND_ENABLED-false}
      GRAPHQL_TRACING_ENABLED: ${GRAPHQL_TRACING_ENABLED-false}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      CDN_ASSET_HOSTNAME: ${CDN_ASSET_HOSTNAME-cdn.baseplatform.io}
      CDN_IMAGE_HOSTNAME: ${CDN_IMAGE_HOSTNAME-base.imgix.net}
      PORT: 80
      EXPOSED_PORT: 10100
    depends_on:
      - mongodb
      - redis
      - google-data-api
    ports:
      - "10100:80"

  graphql-server-leonis:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_PLAYGROUND_ENABLED: 1
      MONGO_DSN: ${MONGO_DSN_LEONIS-mongodb://mongodb:27017}
      REDIS_CACHE_DSN: ${REDIS_CACHE_DSN_LEONIS-redis://redis}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      PORT: 80
      EXPOSED_PORT: 10101
    depends_on:
      - mongodb
      - redis
      - google-data-api
    ports:
      - "10101:80"

  graphql-server-tauron:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_PLAYGROUND_ENABLED: 1
      MONGO_DSN: ${MONGO_DSN_TAURON-mongodb://mongodb:27017}
      REDIS_CACHE_DSN: ${REDIS_CACHE_DSN_TAURON-redis://redis}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      PORT: 80
      EXPOSED_PORT: 10102
    depends_on:
      - mongodb
      - redis
      - google-data-api
    ports:
      - "10102:80"

  graphql-server-virgon:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_PLAYGROUND_ENABLED: 1
      MONGO_DSN: ${MONGO_DSN_VIRGON-mongodb://mongodb:27017}
      REDIS_CACHE_DSN: ${REDIS_CACHE_DSN_VIRGON-redis://redis}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      PORT: 80
      EXPOSED_PORT: 10103
    depends_on:
      - mongodb
      - redis
      - google-data-api
    ports:
      - "10103:80"

  # RSS

  rss:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10200
    depends_on:
      - graphql-server
    ports:
      - "10200:80"

  rss-leonis:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server-leonis
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10201
    depends_on:
      - graphql-server-leonis
    ports:
      - "10201:80"

  rss-tauron:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server-tauron
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10202
    depends_on:
      - graphql-server-tauron
    ports:
      - "10202:80"

  rss-virgon:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server-virgon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10203
    depends_on:
      - graphql-server-virgon
    ports:
      - "10203:80"

  # SITEMAPS

  sitemaps:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10300
    depends_on:
      - graphql-server
    ports:
      - "10300:80"

  sitemaps-leonis:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server-leonis
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10301
    depends_on:
      - graphql-server-leonis
    ports:
      - "10301:80"

  sitemaps-tauron:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server-tauron
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10302
    depends_on:
      - graphql-server-tauron
    ports:
      - "10302:80"

  sitemaps-virgon:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: http://graphql-server-virgon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10303
    depends_on:
      - graphql-server-virgon
    ports:
      - "10303:80"

  # EXAMPLES / OTHER

  example-export:
    <<: *node
    working_dir: /base-cms/services/example-export
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: *env
      GRAPHQL_URI: ${GRAPHQL_URI-http://graphql-server-tauron}
      TENANT_KEY: ${EXAMPLE_TENANT_KEY-p1_sandbox}
      EXPOSED_HOST: exports.dev.parameter1.com
      EXPOSED_PORT: 51270
      PORT: 80
    hostname: exports.dev.parameter1.com
    depends_on:
      - graphql-server-tauron
    ports:
      - "51270:80"

  example-website:
    <<: [*node]
    working_dir: /base-cms/services/example-website
    entrypoint: ["yarn"]
    command: ["dev"]
    environment:
      <<: [*env, *env-tauron]
      PORT: 80
      EXPOSED_PORT: 51269
      LIVERELOAD_PORT: 61269
      TENANT_KEY: ${EXAMPLE_TENANT_KEY-p1_sandbox}
      HOST: www-p1-sandbox.dev.parameter1.com
      SITE_ID: ${EXAMPLE_SITE_ID-5ed294c6c13a4626008b4568}

      # Debug logging
      DEBUG: ${DEBUG-defer,p1events,omeda,content-meter}

      IDENTITYX_GRAPHQL_URI: ${EXAMPLE_IDENTITYX_GRAPHQL_URI-}
      IDENTITYX_APP_ID: ${EXAMPLE_IDENTITYX_APP_ID-5d1b86070ce467bff670a052}
      IDENTITYX_API_TOKEN: ${EXAMPLE_IDENTITYX_API_TOKEN-}

      OMEDA_ENABLED: ${EXAMPLE_OMEDA_ENABLED-0}
      OMEDA_CLIENT_KEY: ${EXAMPLE_OMEDA_CLIENT_KEY-client_acbm}
      OMEDA_GRAPHQL_URI: ${EXAMPLE_OMEDA_GRAPHQL_URI-}
      OMEDA_BRAND_KEY: ${EXAMPLE_OMEDA_BRAND_KEY-hcl}
      OMEDA_APP_ID: ${EXAMPLE_OMEDA_APP_ID}
      OMEDA_INPUT_ID: ${EXAMPLE_OMEDA_INPUT_ID}
      OMEDA_RAPID_IDENT_PRODUCT_ID: ${EXAMPLE_OMEDA_RAPID_IDENT_PRODUCT_ID-15289}
      RECAPTCHA_V3_SECRET_KEY: ${EXAMPLE_RECAPTCHA_V3_SECRET_KEY-}
      RECAPTCHA_V3_SITE_KEY: ${EXAMPLE_RECAPTCHA_V3_SITE_KEY-}
      SENDGRID_API_KEY: ${EXAMPLE_SENDGRID_API_KEY-}

      AUTH0_ENABLED: ${EXAMPLE_AUTH0_ENABLED-0}
      AUTH0_ISSUER_URL: ${EXAMPLE_AUTH0_ISSUER_URL-https://parameter1.us.auth0.com}
      AUTH0_CLIENTID: ${EXAMPLE_AUTH0_CLIENTID-1O2py91c6ZEbN1xqm1smD9jOcULvO2sx}
      AUTH0_SECRET: ${EXAMPLE_AUTH0_SECRET-}
      AUTH0_BASEURL: ${EXAMPLE_AUTH0_BASEURL-http://www-p1-sandbox.dev.parameter1.com:51269}

    hostname: www-p1-sandbox.dev.parameter1.com
    ports:
      - "51269:80"
      - "61269:61269"

  example-leaders-program:
    << : *node
    working_dir: /base-cms/packages/leaders-program
    entrypoint: ["/base-cms/node_modules/.bin/vue-cli-service"]
    command: ["serve", "src/dev.js", "--port", "10400"]
    environment:
      <<: *env
    ports:
      - "10400:10400"

  hooks:
    << : *node
    working_dir: /base-cms/services/hooks
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-mongo, *env-newrelic]
      VIRGON_DSN: ${VIRGON_DSN-mongodb://mongodb:27017}
      TAURON_DSN: ${TAURON_DSN-mongodb://mongodb:27017}
      LEONIS_DSN: ${LEONIS_DSN-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-false}
    depends_on:
      - mongodb
    ports:
      - "10401:80"

  oembed:
    << : *node
    working_dir: /base-cms/services/oembed
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      REDIS_CACHE_DSN: ${REDIS_CACHE_DSN-redis://redis}
      EMBEDLY_API_KEY: ${EMBEDLY_API_KEY-}
      EXPOSED_PORT: 10402
    depends_on:
      - redis
    ports:
      - "10402:80"

  google-data-api:
    << : *node
    working_dir: /base-cms/services/google-data-api
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GOOGLE_DATA_MONGO_DSN: ${GOOGLE_DATA_MONGO_DSN-mongodb://mongodb}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      PORT: 80
      EXPOSED_PORT: 10403
    depends_on:
      - mongodb
    ports:
      - "10403:80"

  omail-link-processor-virgon:
    <<: *node
    working_dir: /base-cms/services/omail-link-processor
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: [*env, *env-newrelic]
      GRAPHQL_URI: ${GRAPHQL_URI-http://graphql-server-virgon}
      PORT: 80
      EXPOSED_PORT: 10404
    depends_on:
      - graphql-server-virgon
    ports:
      - "10404:80"


volumes:
  esdata: {}
  mongodb: {}
  yarn-cache: {}
