version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  TERMINUS_TIMEOUT: 1000
  TERMINUS_SHUTDOWN_DELAY: 0

x-env-newrelic: &env-newrelic
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-mongo: &env-mongo
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
  ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}

x-env-elastic: &env-elastic
  ELASTICSEARCH_URL: ${ELASTICSEARCH_URL-http://elasticsearch:9200}

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /base-cms
  volumes:
    - .:/base-cms:cached
    - ./node_modules:/base-cms/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /base-cms
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "10000:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      server.name: kibana
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL-http://elasticsearch:9200}"
      LOGGING_QUIET: "true"
    depends_on:
      - elasticsearch
    ports:
      - "10001:5601"

  keyword-analysis:
    << : *node
    working_dir: /base-cms/services/keyword-analysis
    command: ["src"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      <<: *env-elastic
    depends_on:
      - mongodb
      - elasticsearch
      - kibana

  # GRAPHQL

  graphql-server:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      APOLLO_ENGINE_ENABLED: ${APOLLO_ENGINE_ENABLED-false}
      APOLLO_ENGINE_API_KEY: ${APOLLO_ENGINE_API_KEY-}
      GRAPHQL_CACHE_CONTROL_ENABLED: ${GRAPHQL_CACHE_CONTROL_ENABLED-false}
      GRAPHQL_DEBUG_ENABLED: ${GRAPHQL_DEBUG_ENABLED-false}
      GRAPHQL_INTROSPECTION_ENABLED: ${GRAPHQL_INTROSPECTION_ENABLED-true}
      GRAPHQL_PLAYGROUND_ENABLED: ${GRAPHQL_PLAYGROUND_ENABLED-false}
      GRAPHQL_TRACING_ENABLED: ${GRAPHQL_TRACING_ENABLED-false}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      CDN_ASSET_HOSTNAME: ${CDN_ASSET_HOSTNAME-cdn.baseplatform.io}
      CDN_IMAGE_HOSTNAME: ${CDN_IMAGE_HOSTNAME-base.imgix.net}
      PORT: 80
      EXPOSED_PORT: 10002
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "10002:80"

  graphql-server-aerilon:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_PLAYGROUND_ENABLED: 1
      MONGO_DSN: ${MONGO_DSN_AERILON-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      PORT: 80
      EXPOSED_PORT: 11000
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11000:80"

  graphql-server-caprica:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_PLAYGROUND_ENABLED: 1
      MONGO_DSN: ${MONGO_DSN_CAPRICA-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      PORT: 80
      EXPOSED_PORT: 11001
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11001:80"

  graphql-server-picon:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_PLAYGROUND_ENABLED: 1
      MONGO_DSN: ${MONGO_DSN_PICON-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      PORT: 80
      EXPOSED_PORT: 11002
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11002:80"

  graphql-server-gemenon:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_PLAYGROUND_ENABLED: 1
      MONGO_DSN: ${MONGO_DSN_GEMENON-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
      BASE4_REST_USERNAME: ${BASE4_REST_USERNAME-}
      BASE4_REST_PASSWORD: ${BASE4_REST_PASSWORD-}
      TOKEN_SECRET: ${TOKEN_SECRET-ThisValueIsNotSecretChangeIt}
      TOKEN_NAMESPACE: ${TOKEN_NAMESPACE-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}
      PORT: 80
      EXPOSED_PORT: 11008
    depends_on:
      - mongodb
      - google-data-api
    ports:
      - "11008:80"

  # RSS

  rss:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10011
    depends_on:
      - graphql-server
    ports:
      - "10011:80"

  rss-aerilon:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-aerilon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11002
    depends_on:
      - graphql-server-aerilon
    ports:
      - "11002:80"

  rss-caprica:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-caprica
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11003
    depends_on:
      - graphql-server-caprica
    ports:
      - "11003:80"

  rss-picon:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-picon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11004
    depends_on:
      - graphql-server-picon
    ports:
      - "11004:80"

  rss-gemenon:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-gemenon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11009
    depends_on:
      - graphql-server-gemenon
    ports:
      - "11009:80"

  # SITEMAPS

  sitemaps:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 10009
    depends_on:
      - graphql-server
    ports:
      - "10009:80"

  sitemaps-aerilon:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-aerilon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11005
    depends_on:
      - graphql-server-aerilon
    ports:
      - "11005:80"

  sitemaps-caprica:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-caprica
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11006
    depends_on:
      - graphql-server-caprica
    ports:
      - "11006:80"

  sitemaps-picon:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-picon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11007
    depends_on:
      - graphql-server-picon
    ports:
      - "11007:80"

  sitemaps-gemenon:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: http://graphql-server-gemenon
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      PORT: 80
      EXPOSED_PORT: 11010
    depends_on:
      - graphql-server-gemenon
    ports:
      - "11010:80"

  # EXAMPLES
  example-leaders-program:
    << : *node
    working_dir: /base-cms/packages/leaders-program
    entrypoint: ["/base-cms/node_modules/.bin/vue-cli-service"]
    command: ["serve", "src/dev.js", "--port", "11164"]
    environment:
      <<: *env
    ports:
      - "11164:11164"

  haproxy:
    image: haproxy:alpine
    ports: [ "${PORT-10010}:80" ]
    volumes:
      - ./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - example-website-lfw
      - graphql-server

  hooks:
    << : *node
    working_dir: /base-cms/services/hooks
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      CAPRICA_DSN: ${CAPRICA_DSN-mongodb://mongodb:27017}
      AERILON_DSN: ${AERILON_DSN-mongodb://mongodb:27017}
      PICON_DSN: ${PICON_DSN-mongodb://mongodb:27017}
      GEMENON_DSN: ${GEMENON_DSN-mongodb://mongodb:27017}
      LEONIS_DSN: ${LEONIS_DSN-mongodb://mongodb:27017}
      TAURON_DSN: ${TAURON_DSN-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-false}
    depends_on:
      - mongodb
    ports:
      - "10012:80"

  oembed:
    << : *node
    working_dir: /base-cms/services/oembed
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      EMBEDLY_API_KEY: ${EMBEDLY_API_KEY-}
    ports:
      - "10013:80"

  google-data-api:
    << : *node
    working_dir: /base-cms/services/google-data-api
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GOOGLE_DATA_MONGO_DSN: ${GOOGLE_DATA_MONGO_DSN-mongodb://mongodb}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      PORT: 80
      EXPOSED_PORT: 10014
    depends_on:
      - mongodb
    ports:
      - "10014:80"

  omail-link-processor-caprica:
    <<: *node
    working_dir: /base-cms/services/omail-link-processor
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      GRAPHQL_URI: ${GRAPHQL_URI-http://graphql-server-caprica}
      PORT: 80
      EXPOSED_PORT: 10015
    depends_on:
      - graphql-server-caprica
    ports:
      - "10015:80"


volumes:
  esdata: {}
  mongodb: {}
  yarn-cache: {}
